
let dados = [
    {
        categoria: "Ales",
        subcategoria: "American Ale",
        nome: "American IPA",
        impressoesGerais: "Cerveja lupulada, sabor cítrico e frutado.",
        aparencia: "Âmbar, turva, espuma densa.",
        aroma: "Lúpulo cítrico e tropical, frutas tropicais.",
        sabor: "Amargor intenso, sabor cítrico e frutado, final seco.",
        sensacaoDeBoca: "Corpo médio, carbonatação alta.",
        ABV: "6-7.5%",
        IBU: "60-100",
        SRM: "6-14",
        harmonizacao: "Hambúrgueres, asas de frango, queijos azuis"
    },
    {
        categoria: "Ales",
        subcategoria: "American Ale",
        nome: "American Pale Ale",
        impressoesGerais: "Cerveja lupulada, sabor maltado balanceado.",
        aparencia: "Âmbar claro, transparente, espuma cremosa.",
        aroma: "Lúpulo floral e cítrico, leve malte.",
        sabor: "Amargor moderado, sabor maltado, final limpo.",
        sensacaoDeBoca: "Corpo médio, carbonatação moderada.",
        ABV: "5-6%",
        IBU: "30-45",
        SRM: "5-10",
        harmonizacao: "Frango assado, saladas, queijos leves"
    },
    {
        categoria: "Ales",
        subcategoria: "English Ale",
        nome: "English Pale Ale",
        impressoesGerais: "Cerveja equilibrada, malte e lúpulo em harmonia.",
        aparencia: "Âmbar claro, transparente, espuma cremosa.",
        aroma: "Malte caramelo, lúpulo floral e cítrico.",
        sabor: "Malte caramelo, leve amargor, final limpo.",
        sensacaoDeBoca: "Corpo médio, carbonatação moderada.",
        ABV: "5-6%",
        IBU: "30-45",
        SRM: "5-10",
        harmonizacao: "Frango assado, saladas, queijos leves"
    },
    {
        categoria: "Lagers",
        subcategoria: "German Lager",
        nome: "Pilsner",
        impressoesGerais: "Cerveja clara, refrescante, levemente lupulada.",
        aparencia: "Dourada, transparente, espuma branca.",
        aroma: "Malte leve, lúpulo floral.",
        sabor: "Malte leve, leve amargor, final limpo.",
        sensacaoDeBoca: "Corpo leve, carbonatação alta.",
        ABV: "4.5-5.5%",
        IBU: "25-40",
        SRM: "3-5",
        harmonizacao: "Saladas, frutos do mar, carnes brancas"
    },
    {
        categoria: "Wheat Beers",
        subcategoria: "German Wheat",
        nome: "Hefeweizen",
        impressoesGerais: "Cerveja de trigo turva, com notas de banana e cravo.",
        aparencia: "Âmbar dourado, turva, espuma densa.",
        aroma: "Banana, cravo, levedura.",
        sabor: "Doce, levemente ácido, com notas de banana e cravo.",
        sensacaoDeBoca: "Corpo médio, carbonatação alta.",
        ABV: "5-5.5%",
        IBU: "10-15",
        SRM: "8-10",
        harmonizacao: "Frutas, queijos suaves, pratos leves"
    },
    {
        categoria: "Stouts",
        subcategoria: "English Stout",
        nome: "Stout",
        impressoesGerais: "Cerveja escura, robusta, com notas de café e chocolate.",
        aparencia: "Preta, cremosa, espuma densa.",
        aroma: "Malte torrado, café, chocolate, frutas secas.",
        sabor: "Doce, torrado, café, chocolate, final seco.",
        sensacaoDeBoca: "Corpo encorpado, carbonatação baixa.",
        ABV: "4-8%",
        IBU: "20-60",
        SRM: "30-40",
        harmonizacao: "Carnes vermelhas, sobremesas, queijos azuis"
    },
    {
        categoria: "Belgian Ales",
        subcategoria: "Belgian Ale",
        nome: "Belgian Tripel",
        impressoesGerais: "Cerveja forte, alcoólica, com notas frutadas e especiadas.",
        aparencia: "Âmbar dourado, transparente, espuma branca.",
        aroma: "Frutas secas, especiarias (coentro, laranja), levemente fenólico.",
        sabor: "Doce, alcoólico, com notas de frutas secas, especiarias e leve amargor.",
        sensacaoDeBoca: "Corpo encorpado, carbonatação alta.",
        ABV: "8-11%",
        IBU: "20-35",
        SRM: "5-10",
        harmonizacao: "Queijos azuis, carnes assadas, sobremesas"
    },
    {
        categoria: "Sours",
        subcategoria: "Lambic",
        nome: "Gueuze",
        impressoesGerais: "Blend de lambics jovens e velhos, acidez pronunciada, com notas de frutas e especiarias.",
        aparencia: "Âmbar dourado, turva, com sedimentos, espuma fina.",
        aroma: "Azedo, vinoso, com notas de frutas vermelhas, especiarias e leve funk.",
        sabor: "Azedo, seco, com notas de frutas vermelhas, especiarias e leve salinidade.",
        sensacaoDeBoca: "Corpo leve a médio, carbonatação alta, textura áspera.",
        ABV: "5-6%",
        IBU: "1-5",
        SRM: "3-5",
        harmonizacao: "Ostras, frutos do mar, queijos leves, sobremesas ácidas"
    },
    {
        categoria: "Ales",
        subcategoria: "Strong Ale",
        nome: "English Barleywine",
        impressoesGerais: "Cerveja forte, alcoólica, com notas de frutas secas, caramelo e lúpulo.",
        aparencia: "Âmbar escuro, transparente, espuma cremosa.",
        aroma: "Frutas secas, caramelo, lúpulo floral, álcool.",
        sabor: "Doce, alcoólico, com notas de frutas secas, caramelo e leve amargor.",
        sensacaoDeBoca: "Corpo encorpado, carbonatação baixa.",
        ABV: "8-12%",
        IBU: "30-50",
        SRM: "20-30",
        harmonizacao: "Queijos azuis, carnes assadas, sobremesas"
    },
    {
        categoria: "Stouts",
        subcategoria: "Irish Dry Stout",
        nome: "Irish Dry Stout",
        impressoesGerais: "Cerveja escura, seca, com notas de café e chocolate.",
        aparencia: "Preta, opaca, espuma marrom.",
        aroma: "Malte torrado, café, chocolate.",
        sabor: "Seco, torrado, café, chocolate, leve amargor.",
        sensacaoDeBoca: "Corpo leve a médio, carbonatação média.",
        ABV: "4-5%",
        IBU: "30-40",
        SRM: "30-40",
        harmonizacao: "Ostras, frutos do mar, queijos azuis"
    },
    {
        categoria: "Ales",
        subcategoria: "Scottish Ale",
        nome: "Scottish Ale",
        impressoesGerais: "Cerveja maltada, com notas de caramelo e frutas secas.",
        aparencia: "Âmbar escuro, opaca, espuma marrom.",
        aroma: "Malte caramelo, frutas secas, leve defumado.",
        sabor: "Doce, maltado, com notas de caramelo e frutas secas.",
        sensacaoDeBoca: "Corpo encorpado, carbonatação baixa.",
        ABV: "5-7%",
        IBU: "20-35",
        SRM: "20-30",
        harmonizacao: "Caçarolas, carnes assadas, queijos fortes"
    },
    {
        categoria: "Ales",
        subcategoria: "Irish Red Ale",
        nome: "Irish Red Ale",
        impressoesGerais: "Cerveja maltada, com notas de caramelo e frutas.",
        aparencia: "Cobre, transparente, espuma bege.",
        aroma: "Malte caramelo, frutas vermelhas, leve torrado.",
        sabor: "Doce, maltado, com notas de caramelo e frutas vermelhas.",
        sensacaoDeBoca: "Corpo médio, carbonatação moderada.",
        ABV: "4-5%",
        IBU: "20-30",
        SRM: "12-17",
        harmonizacao: "Queijos leves, carnes assadas, frango"
    },
    {
        categoria: "Ales",
        subcategoria: "Belgian Ale",
        nome: "Belgian Dubbel",
        impressoesGerais: "Cerveja complexa, com notas frutadas e especiadas.",
        aparencia: "Âmbar escuro, transparente, espuma bege.",
        aroma: "Frutas escuras, especiarias (cravo, pimenta), levemente fenólico.",
        sabor: "Doce, maltado, com notas de frutas escuras, especiarias e leve amargor.",
        sensacaoDeBoca: "Corpo médio, carbonatação moderada.",
        ABV: "6-7%",
        IBU: "20-25",
        SRM: "15-20",
        harmonizacao: "Queijos fortes, carnes assadas, chocolate amargo"
    },
    {
        categoria: "Lagers",
        subcategoria: "German Lager",
        nome: "Märzen",
        impressoesGerais: "Cerveja maltada, com sabor de pão e levemente doce.",
        aparencia: "Âmbar, transparente, espuma branca.",
        aroma: "Malte biscoito, leve floral.",
        sabor: "Maltado, levemente doce, final limpo.",
        sensacaoDeBoca: "Corpo médio, carbonatação moderada.",
        ABV: "5-6%",
        IBU: "18-25",
        SRM: "10-14",
        harmonizacao: "Carnes assadas, salsichas, queijos semi-duros"
    },
    {
        categoria: "Wheat Beers",
        subcategoria: "Belgian Wheat",
        nome: "Witbier",
        impressoesGerais: "Cerveja de trigo turva, com adição de casca de laranja e coentro.",
        aparencia: "Amarelo pálido, turva, espuma branca.",
        aroma: "Laranja, coentro, levedura.",
        sabor: "Cítrico, levemente ácido, com notas de laranja e coentro.",
        sensacaoDeBoca: "Corpo leve, carbonatação alta.",
        ABV: "4.5-5.5%",
        IBU: "10-15",
        SRM: "2-4",
        harmonizacao: "Frutos do mar, saladas, queijos leves"
    },
    {
        categoria: "Stouts",
        subcategoria: "American Stout",
        nome: "American Stout",
        impressoesGerais: "Stout com caráter americano, mais lupulado e com maior variedade de sabores.",
        aparencia: "Preta, opaca, espuma marrom.",
        aroma: "Malte torrado, café, chocolate, frutas secas, lúpulo cítrico.",
        sabor: "Amargor moderado a alto, torrado, café, chocolate, final seco.",
        sensacaoDeBoca: "Corpo médio a encorpado, carbonatação moderada.",
        ABV: "5-8%",
        IBU: "30-60",
        SRM: "30-40",
        harmonizacao: "Carnes vermelhas grelhadas, queijos azuis, sobremesas de chocolate"
    },
    {
        categoria: "Sours",
        subcategoria: "Berliner Weisse",
        nome: "Berliner Weisse",
        impressoesGerais: "Cerveja ácida e refrescante, com adição de frutas ou xarope.",
        aparencia: "Amarelo pálido, turva, espuma branca.",
        aroma: "Azedo, levemente frutado (framboesa, morango), levemente fenólico.",
        sabor: "Azedo, seco, levemente salgado, com notas de fruta.",
        sensacaoDeBoca: "Corpo leve, carbonatação alta.",
        ABV: "3-4%",
        IBU: "5-10",
        SRM: "2-4",
        harmonizacao: "Frutos do mar, saladas, pratos leves"
    },
    {
        categoria: "Lagers",
        subcategoria: "German Lager",
        nome: "Dunkel",
        impressoesGerais: "Lager escura, com sabor maltado e levemente doce.",
        aparencia: "Marrom escuro, transparente, espuma bege.",
        aroma: "Malte caramelo, chocolate, leve torrado.",
        sabor: "Doce, maltado, com notas de chocolate e leve amargor.",
        sensacaoDeBoca: "Corpo médio, carbonatação moderada.",
        ABV: "4.5-5.5%",
        IBU: "18-25",
        SRM: "15-20",
        harmonizacao: "Carnes assadas, queijos semi-duros, pratos defumados"
    },
    {
        categoria: "Wheat Beers",
        subcategoria: "American Wheat",
        nome: "American Wheat Beer",
        impressoesGerais: "Cerveja de trigo americana, mais leve e refrescante.",
        aparencia: "Amarelo pálido, turva, espuma branca.",
        aroma: "Lúpulo cítrico, levemente frutado.",
        sabor: "Cítrico, levemente doce, final limpo.",
        sensacaoDeBoca: "Corpo leve, carbonatação alta.",
        ABV: "4-5%",
        IBU: "10-15",
        SRM: "2-4",
        harmonizacao: "Frango grelhado, saladas, frutos do mar"
    },
];